version: '3.8'
services:
  auth-service:
    build: .
    container_name: auth-service
    # ports:
    #  - "80:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - auth-db-net
      - api-net
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      POSTGRES_DB: ${AUTH_DATABASE_NAME}
    command: "-p ${AUTH_DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DATABASE_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - auth-db-net

volumes:
  auth-data:
    name: auth-data

networks:
  auth-db-net:
  api-net:
    external: true